// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SkipTitle","status":true,"description":"Skip the title screen and go directly to the map.","parameters":{}},
{"name":"JokeTeller","status":true,"description":"Tells a random joke from jokes.json and displays it in message chunks.","parameters":{}},
{"name":"Community_Basic","status":false,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}}
];
